on: issue_comment

name: Example

jobs:
  parse-comment:
    runs-on: ubuntu-latest
    if: ${{ github.event.issue.pull_request }}
    outputs:
      command: ${{ steps.parse-comment.outputs.command }}
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: parse-comment
        with:
          comment: ${{ toJSON(github.event.comment) }}
          commands: |
            /format
            /repackage
          github-token: ${{ secrets.GITHUB_TOKEN }}

  format:
    runs-on: ubuntu-latest
    needs: [parse-comment]
    if: ${{ needs.parse-comment.outputs.command == '/format' }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: Install
        run: npm install
      - name: Format
        run: npm run format
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: Commit Changes
        id: auto-commit-action
        with:
          commit_message: autoformat
      - name: Comment No-Changes
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'ðŸ¤– Nothing to format!'
            })

  repackage:
    runs-on: ubuntu-latest
    needs: [parse-comment]
    if: ${{ needs.read-comment.outputs.command == '/repackage' }}
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
      - name: Install
        run: npm install
      - name: Build
        run: npm run build
      - name: Format
        run: npm run format
      - uses: stefanzweifel/git-auto-commit-action@v4
        name: Commit Changes
        id: auto-commit-action
        with:
          commit_message: repackage
      - name: Comment No-Changes
        if: steps.auto-commit-action.outputs.changes_detected == 'false'
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: 'ðŸ¤– Nothing to repackage!'
            })
